"""Initial database schema

Revision ID: b6e4aab02f04
Revises: f7889d3cb0dd
Create Date: 2025-01-13 11:55:40.220138

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'b6e4aab02f04'
down_revision = 'f7889d3cb0dd'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('pet_sitters',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(), nullable=False),
    sa.Column('location', sa.String(), nullable=False),
    sa.Column('price', sa.Integer(), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('name')
    )
    op.create_table('appointments',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('date', sa.DateTime(), nullable=False),
    sa.Column('duration', sa.Integer(), nullable=False),
    sa.Column('pet_owners_id', sa.Integer(), nullable=False),
    sa.Column('pet_sitters_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['pet_owners_id'], ['pet_owners.id'], ),
    sa.ForeignKeyConstraint(['pet_sitters_id'], ['pet_sitters.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('pets',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('pet_name', sa.String(), nullable=False),
    sa.Column('pet_type', sa.String(), nullable=False),
    sa.Column('owner_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['owner_id'], ['pet_owners.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('pet_name'),
    sa.UniqueConstraint('pet_type')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('pets')
    op.drop_table('appointments')
    op.drop_table('pet_sitters')
    # ### end Alembic commands ###
